### ISSUE TITLE
Move vino-builder from Images repo to ViNO

### ISSUE THREAD

**Issue by lb4368** [airshipit/vino#5]
**Problem description**
Due to the tight coupling of the ViNO operator and vino-builder, it is suggested to move the vino-builder code development from its current location in the Images repo (https://github.com/airshipit/images/tree/master/vino-builder) to ViNO so that development and CI for vino-builder can be managed along with the ViNO operator.

**Proposed change**
Move the vino-builder code from Images repo into the ViNO repo.  

Suggestion would be to move it to a images/vino-builder folder within the ViNO repo.  Then update the ViNO Makefile to include targets for building and pushing the vino-builder image.

**Comment by DanCrank-att** [comment]
@lb4368 I can work on this.

**Comment by lb4368** [comment]
Thanks @DanCrank-att !

**Comment by DanCrank-att** [comment]
WIP:

https://review.opendev.org/c/airship/vino/+/786713 to move vino-builder to vino repo
https://review.opendev.org/c/airship/images/+/786714 to remove vino-builder from images repo

**Comment by DanCrank-att** [comment]
Patchsets ready for review.

**Comment by DanCrank-att** [comment]
https://review.opendev.org/c/airship/vino/+/786713 and https://review.opendev.org/c/airship/images/+/786714 are now merged.
