### ISSUE TITLE
Support Single libvirt Network for VMs Created By ViNO

### ISSUE THREAD

**Issue by lb4368** [airshipit/vino#9]
**Proposed change**
Update ViNO to support using a single libvirt network interface to support both the _vm-infra-bridge_ for network traffic generated from the VMs and PXE for VM deployment.

**Comment by lb4368** [comment]
Related PS: https://review.opendev.org/c/airship/vino/+/795534

**Comment by teoyaomiqui** [comment]
Closing per merged patchset
